### ISSUE TITLE
X-Forwarded-For & X-Real-IP

### ISSUE THREAD

**Issue by andruwa13** [travisghansen/kubernetes-pfsense-controller#18]
Add X-Real-IP & X-Forwarded-For are the private ip addr of the ingress controller.

**Comment by travisghansen** [comment]
Welcome! Also, huh? I have no idea what you’re asking.

**Comment by andruwa13** [comment]
@travisghansen  In the nginx logs internal IP, but I need to have a real IP

**Comment by travisghansen** [comment]
You’re terminating on haproxy on pfsense and then using this project to create shared frontends to forward to your ingress controller?

**Comment by andruwa13** [comment]
yes

**Comment by travisghansen** [comment]
Just check `use forwardfor` in the `advanced` settings for the frontend. You can optionally put something like this in the `advanced pass thru` in that same section:

```
http-request set-header X-Forwarded-Ssl on if { ssl_fc }
http-request set-header X-Forwarded-Port %[dst_port]
http-request set-header X-Real-Ip %[src]
```

**Comment by andruwa13** [comment]
not work(

**Comment by travisghansen** [comment]
This really isn’t managed by this project. Sorry :(
