### ISSUE TITLE
Where do I actually put the plugins?

### ISSUE THREAD

**Issue by 2fst4u** [travisghansen/kubernetes-pfsense-controller#24]
This looks like exactly what I'm looking for and I'm familiar with deploying via helm, but forgive me where do I actually put the plugin configs? I can't see the settings in the values.yml

I'm sure I'm missing something simple.

**Comment by travisghansen** [comment]
Welcome! https://github.com/travisghansen/kubernetes-pfsense-controller-chart/blob/master/stable/kubernetes-pfsense-controller/templates/config.yaml#L10

**Comment by travisghansen** [comment]
https://github.com/travisghansen/kubernetes-pfsense-controller-chart/blob/master/stable/kubernetes-pfsense-controller/values.yaml#L11-L16

**Comment by 2fst4u** [comment]
AHA I knew it would be something silly. Thank you.

Next question though, I can't figure out how to add my pfsense password as an existing secret rather than putting it in the values.yml. Can that be done?

**Comment by 2fst4u** [comment]
Never mind I just templated the chart instead and used my own secret. I have other issues though so I'll open new issues for them. Thanks.
