### ISSUE TITLE
Cannot change namespace

### ISSUE THREAD

**Issue by aded** [travisghansen/kubernetes-pfsense-controller#7]
Hi @travisghansen, thanks for this controller, it's very useful!

When I try to change the namespace (basically s/kube-system/mynamespace/ on each k8s manifest file), I'm able to deploy the controller, but I get the following messages in pod logs:

```
2020-03-25T18:02:34+00:00 waiting for ConfigMap kube-system/kubernetes-pfsense-controller-config to be present and valid
``` 

It seems it waits for kubernetes-pfsense-controller-config on kube-system namespace only.

PS: I'm relatively new in Kubernetes, so I apologize if this is the desired behaviour.

Thanks in advance!

**Comment by travisghansen** [comment]
@aded thanks for the interest! That does look to be hard-coded currently :( I'll have to code that in.

**Comment by travisghansen** [comment]
This is configurable now via the `CONTROLLER_NAMESPACE` env var. Note that you'll like need to update the `rbac` stuff if you're actually deploying the pod to a different namespace as well.

**Comment by travisghansen** [comment]
`v0.2.0`
