### ISSUE TITLE
dns update error

### ISSUE THREAD

**Issue by softwaredelcentro** [travisghansen/kubernetes-pfsense-controller#9]
Installed latest git master version.

I get pfsense Incorrect parameters passed to method: Signature permits 2 parameters but the request had 1 (3) when it tries to update pfsense

using only dns service, only unbound

excelente project!

**Comment by travisghansen** [comment]
Interesting, can you send over the full logs (email is fine if something is sensitive)? Also it would be good to see your configuration yaml.

**Comment by softwaredelcentro** [comment]
Sure.. configmap :

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kube-system
  name: kubernetes-pfsense-controller-config
data:
  config: |
    controller-id: "desarrollo"
    enabled: true
    plugins:
      metallb:
        enabled: false
        nodeLabelSelector:
        nodeFieldSelector:
        #configMap: "metallb-system/config"
        # pick 1 implementation
        bgp-implementation: openbgp
        # bgp-implementation: frr
        options:
          openbgp:
            # pass through to config.xml
            template:
              md5sigkey:
              md5sigpass:
              groupname: metallb
              row:
                - parameters: announce all
                  parmvalue:
          frr:
            template:
              peergroup: metallb
      haproxy-declarative:
        enabled: false
      haproxy-ingress-proxy:
        enabled: false
        ingressLabelSelector:
        ingressFieldSelector:
        defaultFrontend: http-80
        defaultBackend: traefik
        # by default anything is allowed
        #allowedHostRegex: "/.*/"
      pfsense-dns-services:
        enabled: true
        serviceLabelSelector:
        serviceFieldSelector:
        #allowedHostRegex: "/.*/"
        dnsBackends:
          dnsmasq:
            enabled: false
          unbound:
            enabled: true
      pfsense-dns-ingresses:
        enabled: false
        ingressLabelSelector:
        ingressFieldSelector:
        #allowedHostRegex: "/.*/"
        dnsBackends:
          dnsmasq:
            enabled: true
          unbound:
            enabled: true
      pfsense-dns-haproxy-ingress-proxy:
        enabled: false
        #allowedHostRegex: "/.*/"
        dnsBackends:
          dnsmasq:
            enabled: true
          unbound:
            enabled: true
        frontends:
          http-80:
            hostname: http-80.k8s
          primary_frontend_name2:
            hostname: some-name.k8s

**Comment by softwaredelcentro** [comment]
deployment.yaml:

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kubernetes-pfsense-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-pfsense-controller
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kubernetes-pfsense-controller
    spec:
      serviceAccountName: kubernetes-pfsense-controller
      containers:
        - name: kubernetes-pfsense-controller
          image: docker.io/travisghansen/kubernetes-pfsense-controller:v0.1.9
          env:
            - name: PFSENSE_URL
              value: "http://172.16.1.1"
              # allow self-signed certs
            - name: PFSENSE_INSECURE
              value: "true"
            - name: PFSENSE_USERNAME
              value: "admin"
            - name: PFSENSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kubernetes-pfsense-controller
                  key: pfsense-password

**Comment by softwaredelcentro** [comment]
rbac.yaml: untoched

**Comment by softwaredelcentro** [comment]
pfsense:

Version | 2.3.5-RELEASE-p2 (i386)built on Thu May 10 15:03:18 CDT 2018FreeBSD 10.3-RELEASE-p29The system is on the latest version.Version information updated at 2020-04-16 19:45
-- | --

**Comment by softwaredelcentro** [comment]
podlog:

2020-04-16T22:47:48+00:00 store successfully initialized
2020-04-16T22:47:49+00:00 waiting for ConfigMap kube-system/kubernetes-pfsense-controller-config to be present and valid
2020-04-16T22:47:54+00:00 controller config loaded/updated
2020-04-16T22:47:54+00:00 loading plugin pfsense-dns-services
2020-04-16T22:48:05+00:00 plugin (pfsense-dns-services): failed update/reload: Incorrect parameters passed to method: Signature permits 2 parameters but the request had 1 (3)

**Comment by travisghansen** [comment]
fun...this started happening *after* updating to the latest version but was working previously?

**Comment by softwaredelcentro** [comment]
Just installed for the first time today

**Comment by travisghansen** [comment]
Ok, I'm guessing it's a difference in pfsense versions. I'm not sure if I ever ran it against 2.3. I'll do an install of 2.3 and have a look...

**Comment by travisghansen** [comment]
It looks like pfsense does not allow downloading older versions as they are considered insecure...can you update to 2.4 and try?

**Comment by travisghansen** [comment]
Any luck with a newer version?
